// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4aSX5KPvhg42to5Ud5_ty0twE--o9Nwg',
    appId: '1:1033457552496:web:33492612f79b4e0b3ff8b5',
    messagingSenderId: '1033457552496',
    projectId: 'easydrive-app-d8787',
    authDomain: 'easydrive-app-d8787.firebaseapp.com',
    storageBucket: 'easydrive-app-d8787.firebasestorage.app',
    measurementId: 'G-KEP14XZKJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARP3GK-SEgQCq1tfgvdssKunwlhp4q6V8',
    appId: '1:1033457552496:android:ccae31ffe0fc82573ff8b5',
    messagingSenderId: '1033457552496',
    projectId: 'easydrive-app-d8787',
    storageBucket: 'easydrive-app-d8787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoOmE4arlUInfhUgK1G8mSVB1Y0Xzwm_w',
    appId: '1:1033457552496:ios:a1713f4ff88f082c3ff8b5',
    messagingSenderId: '1033457552496',
    projectId: 'easydrive-app-d8787',
    storageBucket: 'easydrive-app-d8787.firebasestorage.app',
    iosBundleId: 'com.example.easydrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoOmE4arlUInfhUgK1G8mSVB1Y0Xzwm_w',
    appId: '1:1033457552496:ios:a1713f4ff88f082c3ff8b5',
    messagingSenderId: '1033457552496',
    projectId: 'easydrive-app-d8787',
    storageBucket: 'easydrive-app-d8787.firebasestorage.app',
    iosBundleId: 'com.example.easydrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4aSX5KPvhg42to5Ud5_ty0twE--o9Nwg',
    appId: '1:1033457552496:web:74b88a6b9673bd9e3ff8b5',
    messagingSenderId: '1033457552496',
    projectId: 'easydrive-app-d8787',
    authDomain: 'easydrive-app-d8787.firebaseapp.com',
    storageBucket: 'easydrive-app-d8787.firebasestorage.app',
    measurementId: 'G-RTDY14E28H',
  );
}
